spring:
  liquibase:
    contexts: prod
  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
app:
  url: ${APP_URL}
server:
  address: 0.0.0.0
  port: 8080