spring:
  datasource:
    url: jdbc:mysql://localhost:3306/e_learning_app_db?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
app:
  url: http://localhost:8080
server:
  address: 127.0.0.1
  port: 8080